feat: allow uploading & downloading progress-ink data
BuidlGuidl/nifty-ink pull request #39
Opened 2021-12-09 14:39 UTC by sadda11asm

closes #18

2021-12-09 21:56 UTC, azf20 requested changes
Looks good! I think makes sense to create a section with this and the "Drafts" buttons, as they kind of go together. Small comment on timestamp in the file. Nice work!

2021-12-09 21:56 UTC, azf20 commented on packages/react-app/src/CreateInk.js
> +            <Button
We may want to move these to be next to the "Drafts" buttons (see https://github.com/BuidlGuidl/nifty-ink/pull/35)
I think probably doesn't make sense mixed in with all the drawing tools?

2021-12-09 21:56 UTC, azf20 commented on packages/react-app/src/CreateInk.js
> +  const downloadCanvas = async () => {
Nice!

2021-12-09 21:56 UTC, azf20 commented on packages/react-app/src/CreateInk.js
> +    const fileName = "canvas";
could we maybe include the timestamp here so users can download different files?

2021-12-10 02:17 UTC, davidryan59 approved these changes
I've tested it, works nicely!

<img width="1216" alt="Screenshot 2021-12-10 at 09 14 18" src="https://user-images.githubusercontent.com/11883046/145505907-d5d785c2-f7ef-475c-bedf-4bdef4672dc2.png">

Approved, but a couple of changes would enhance further:
- Put a tooltip on DOWNLOAD button, like the existing one on UPLOAD
- Make the file name timestamped, and referring to Nifty Ink, such as `nifty_ink_canvas_YYYY_MM_DD_HH_mm_SS.json`

2021-12-11 09:06 UTC, sadda11asm commented
fixed all the issues :)

2021-12-11 13:48 UTC, azf20 approved these changes

2021-12-11 13:48 UTC, merged